---
  - name: Stop Instance
    command: forever stop 0

  - name: Backup OPP Folder
    command: mv /opt/OPP /opt/OPP_{{ date }}

  - name: Clone Git Repo
    git:
      repo: "https://{{ git_user | urlencode}}:{{ git_pass }}@appcontrol.ama.lan/OPP/OPP.git"
      dest: /opt/OPP

  - name: PAUSE - NPM Install
    pause:
      prompt: "Execute NPM Install and replace config files" 

  - name: Start Instance
    command: forever start /opt/OPP/server
